# Default initial positions for Estun's ros2_control fake system

initial_positions:
  Umdrehung 1: -0.733
  Umdrehung 2: -0.175
  Umdrehung 3: 2.251
  Umdrehung 4: -2.321
  Umdrehung 5: 1.553
  Umdrehung 6: 2.164