[package]
name = "moveit_task_constructor_msgs"
version = "0.2.0"
edition = "2021"

[dependencies]
rosidl_runtime_rs = "0.6"
serde = { version = "1", optional = true, features = ["derive"] }
serde-big-array = { version = "0.5.1", optional = true }

# ROS Dependencies
action_msgs = "*"
builtin_interfaces = "*"
geometry_msgs = "*"
moveit_msgs = "*"
object_recognition_msgs = "*"
octomap_msgs = "*"
sensor_msgs = "*"
service_msgs = "*"
shape_msgs = "*"
std_msgs = "*"
trajectory_msgs = "*"
unique_identifier_msgs = "*"
visualization_msgs = "*"

[features]
serde = ['dep:serde', 'dep:serde-big-array', 'rosidl_runtime_rs/serde', 'action_msgs/serde', 'builtin_interfaces/serde', 'geometry_msgs/serde', 'moveit_msgs/serde', 'object_recognition_msgs/serde', 'octomap_msgs/serde', 'sensor_msgs/serde', 'service_msgs/serde', 'shape_msgs/serde', 'std_msgs/serde', 'trajectory_msgs/serde', 'unique_identifier_msgs/serde', 'visualization_msgs/serde']

[package.metadata.ros-env]
include = true
